//
// Created by aether on 2/26/20.
//

#ifndef CONCERTATIONREALTIME_MODE_H
#define CONCERTATIONREALTIME_MODE_H


enum Mode {
	RAW, LINES, SPACED_OUT_LINES, RECTANGLES, CIRCLE
};


#endif //CONCERTATIONREALTIME_MODE_H
